ALTER TABLE ALBUM DROP CONSTRAINT ARTIST_ID_exists;
ALTER TABLE TRACK DROP CONSTRAINT ALBUM_ID_exists;
DROP TABLE TRACK;
DROP TABLE ALBUM;
DROP TABLE ARTIST;

CREATE TABLE ALBUM (
    ID SERIAL PRIMARY KEY,
    DISC_ID CHAR(8) UNIQUE,
    NAME VARCHAR(200) UNIQUE,
    YEAR CHAR(4),
    ARTIST_ID INT 
);

CREATE TABLE ARTIST (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) UNIQUE,
    CATEGORY VARCHAR(50)
);

CREATE TABLE TRACK (
    ID SERIAL PRIMARY KEY,
    NUM INT,
    NAME VARCHAR(255),
    ALBUM_ID INT
);

ALTER TABLE ALBUM ADD CONSTRAINT ARTIST_ID_exists FOREIGN KEY (ARTIST_ID) REFERENCES ARTIST (ID);
ALTER TABLE TRACK ADD CONSTRAINT ALBUM_ID_exists FOREIGN KEY (ALBUM_ID) REFERENCES ALBUM (ID);
